package com.flair.client.localization;

/*
 * Tags for common strings
 */
public enum CommonLocalizationTags {
	INVALID,
	BRANDING,
	YES,
	NO,
	OK,
	APPLY,
	CANCEL,
	CLOSE,
	FINISH,
	RESET,
	RESET_ALL,
	NEXT,
	SEARCH,
	UPLOAD,
	COMPARE,
	FILTER,
	OPERATION_INPROGRESS_CONFIRM_TITLE,
	OPERATION_INPROGRESS_CONFIRM_CAPTION,
	WAIT_TILL_COMPLETION,
	RESULT,
	RESULTS,
	LANGUAGE_ENGLISH,
	LANGUAGE_GERMAN,
	ACADEMIC_VOCAB,
	CUSTOM_VOCAB,
	KEYWORDS,
	FEATURE_NOT_SUPPORTED,
	/**
	 TAGS for word export / copy to clipboard.
	 */
	LINK_COPY_TO_CLIPBOARD_SUCCESSFUL,
	COPY_TEXT_FORMATTING,
	TEXT_COPY_TEXT_TO_CLIPBOARD,
	TEXT_SAVE_TEXT_AS_WORD_DOCUMENT,
	SENTENCES,
	WORDS,
	READABILITY_LEVEL,
	NUMBER_OF_SENTENCES,
	NUMBER_OF_WORDS,
	CONSTRUCTION,
	HITS,
	WEIGHT,
	FOOTER_WORD,
	LABEL_LINK_TO_TEXT;

	public String getString() {
		return DefaultLocalizationProviders.COMMON.get()
				.getLocalizedString(this.toString(), LocalizationEngine.get().getLanguage());
	}
}
