package com.flair.client.localization;

import com.flair.client.localization.interfaces.LocalizableEntity;

import java.util.ArrayList;
import java.util.List;

/*
 * Data generated by the localization deferred binder for a given localized composite
 */
public class LocalizationBinderData {
	public final String providerName;
	public final List<LocalizableEntity> localizationWrappers;

	public LocalizationBinderData(String provider) {
		this.providerName = provider;
		this.localizationWrappers = new ArrayList<>();
	}
}
